### ISSUE TITLE
Readings not accurate

### ISSUE THREAD

**Issue by darktim** [peltsippi/ruuvi-hass#1]
Hi,

I just tried out your code, thanks a lot.

Unfortunately the readings are not accurate, as far as I can tell. This is the output of /home/homeassistant/ruuvi-hass/ruuvi-hass.py batch 
for three different MACs

4.15:63.0:1025.99
3.15:63.0:1027.28
120.15:63.0:904.45

This is the output of
python3 /srv/homeassistant/lib/python3.6/site-packages/ruuvitag_sensor -l

{'FA:31:A0:32:60:47': {'humidity': 41.5, 'temperature': 21.3, 'pressure': 969.01, 'acceleration': 1048.1664944082117, 'acceleration_x': 987, 'acceleration_y': -328, 'acceleration_z': 130, 'battery': 3181}, 'C3:E5:A5:2B:D8:10': {'humidity': 38.0, 'temperature': 24.49, 'pressure': 971.24, 'acceleration': 1003.0383841109971, 'acceleration_x': -17, 'acceleration_y': 154, 'acceleration_z': 991, 'battery': 3199}, 'D9:6F:21:16:75:95': {'humidity': 38.0, 'temperature': 24.17, 'pressure': 970.36, 'acceleration': 1015.0354673606238, 'acceleration_x': 6, 'acceleration_y': -6, 'acceleration_z': 1015, 'battery': 3169}}

My knowledge in python is quite limited, can you give me a hint for debugging?

**Comment by darktim** [comment]
I think, I have a hint here. It looks like the code expects eddystone protocol. The newer firmware is sending raw instead.
After toggling into URL Mode (pressing B on the beacon) it works as expected

**Comment by trotor** [comment]
Hi and thank you for giving this hint! I found out that you can actually decode raw too and get more accutrate readings:
Change urldecoder() to Df3Decoder() where you encounter it.

There is also a way to detect which decoder to use, I suppose it is the "encoded[0]  and then use decoder.get_decoder(encoded[0]) and you'll get correct one. 

Also add 
from ruuvitag_sensor.decoder import Df3Decoder
after the urldecoder import just to be sure.

**Comment by peltsippi** [comment]
Old version became obsolete, this is now copy of better solution, configured for post 0.92 Hass and worksforme
