### ISSUE TITLE
Timeout if no value received - Add binary sensor for tag present or not

### ISSUE THREAD

**Issue by oduo** [peltsippi/ruuvi-hass#2]
Hi,

Is there a timeout defined if ruuvitag is not reporting temperature values for some reason?
Let's say I have 3 tags and one is Inside car that goes away daily.
command
/home/homeassistant/ruuvi-hass/ruuvi-hass.py batch E9:B0:C4:AD:19:39 FB:AA:6A:C9:7B:20 C4:E1:36:E9:50:B1 
keeps waiting for ever that tag that is too far away reports values

Also would like to use this feature for binary sensor that is tag present / in range or not

**Comment by peltsippi** [comment]
Old version became obsolete, this is now copy of better solution, configured for post 0.92 Hass and worksforme
